name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3  # Corrected to v3, the latest version
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Create .env file
      run: |
        touch .env
        echo "${{ secrets.PROD_ENV }}" > .env
    
    - name: Ensure PM2 is installed globally
      run: |
        if ! command -v pm2 &> /dev/null; then
          echo "PM2 is not installed. Installing it globally..."
          npm install -g pm2
        else
          echo "PM2 is already installed."
        fi
    
    - name: Restart application with PM2
      run: |
        pm2 describe ci-cd-server > /dev/null
        if [ $? -eq 0 ]; then
          pm2 restart ci-cd-server
        else
          pm2 start npm --name ci-cd-server -- start
        fi
